package com.prashanth.spring.boot.jpa.auto;

import java.util.UUID;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;

import com.prashanth.spring.boot.jpa.auto.entity.OrdersService;

@SpringBootApplication
public class SpringJpaAutoGeneratedValuesApplication {

	public static void main(String[] args) {
		ConfigurableApplicationContext container=SpringApplication.run(SpringJpaAutoGeneratedValuesApplication.class, args);
	OrdersService os=container.getBean(OrdersService.class);
		os.addOrder();
		
		
		
		//System.out.println(UUID.randomUUID());
	}

}
