package com.prashanth.spring.boot.jpa.auto;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class SpringJpaAutoGeneratedValuesApplicationTests {

	@Test
	void contextLoads() {
	}

}
